### ISSUE TITLE
Config File Setup

### ISSUE THREAD

**Issue by jaykepeters** [pboehm/ddns#14]
Ok, so here's what I have setup with my DNS Provider:
A: ns.bluejayit.com -> IP of server
A: ddns.bluejayit.com ->IP of server (Frontend)
NS: dyn.bluejayit.com -> ns.bluejayit.com

I assume that is correct from other tutorials. 

Now in the configuration file, what would these values be?

**Comment by pboehm** [comment]
Please refer to this section https://github.com/pboehm/ddns#ddns-setup and create the corresponding `docker-compose.override.yml` based on this [sample](https://github.com/pboehm/ddns/blob/master/docker/docker-compose.override.yml.sample), which I have adjusted for your DNS setup:

```
version: '2'

services:
  ddns:
    environment:
      DDNS_DOMAIN: dyn.bluejayit.com
      DDNS_SOA_DOMAIN: ddns.bluejayit.com

  powerdns:
    ports:
      - "53:53/udp"

  redis:
    volumes:
      - "/root/ddns-redis:/data"                      # <<< ADJUST LOCAL PATH

  caddy:
    restart: unless-stopped
    image: abiosoft/caddy:latest
    depends_on:
      - ddns
    environment:
      DDNS_FRONTEND_HOST: ddns:8080
      DDNS_CADDY_DOMAIN: ddns.bluejayit.com
      DDNS_CADDY_TLS_EMAIL: changeme@example.net      # <<< INSERT EMAIL
    volumes:
      - "${PWD}/caddy/Caddyfile:/etc/Caddyfile"
      - "/root/ddns-caddy:/root/.caddy"               # <<< ADJUST LOCAL PATH
    ports:
      - "80:80"
      - "443:443"
```
